<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN485900" failures="4" tests="13" name="ZigWheels(Edge)-Test" time="134.128" errors="0" timestamp="2024-04-08T14:42:02 IST">
  <testcase classname="testSuites.TestSuite3_Login" name="valiateLoginButtonIsClickable" time="1.616"/>
  <testcase classname="testSuites.TestSuite1_UpcomingHondaBikes" name="validateNewBikesDropdown" time="13.001"/>
  <testcase classname="testSuites.TestSuite2_UsedCarsInChennai" name="validateUsedCarsDropdown" time="12.022"/>
  <testcase classname="testSuites.TestSuite2_UsedCarsInChennai" name="validateChennaiIsClickable" time="0.122"/>
  <testcase classname="testSuites.TestSuite3_Login" name="validateLoginScreenVisible" time="0.48"/>
  <testcase classname="testSuites.TestSuite1_UpcomingHondaBikes" name="validateUpcomingBikeIsClickable" time="0.114"/>
  <testcase classname="testSuites.TestSuite2_UsedCarsInChennai" name="validateChennaiLink" time="6.599"/>
  <testcase classname="testSuites.TestSuite3_Login" name="validateGoogleButtonIsClickable" time="0.145"/>
  <testcase classname="testSuites.TestSuite1_UpcomingHondaBikes" name="validateUpcomingBikesButton" time="3.04">
    <failure type="java.lang.AssertionError" message="expected [https://www.zigwheels.com/upcoming-bikes] but found [https://www.zigwheels.com/used-car/Chennai]">
      <![CDATA[java.lang.AssertionError: expected [https://www.zigwheels.com/upcoming-bikes] but found [https://www.zigwheels.com/used-car/Chennai]
at testSuites.TestSuite1_UpcomingHondaBikes.validateUpcomingBikesButton(TestSuite1_UpcomingHondaBikes.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- validateUpcomingBikesButton -->
  <testcase classname="testSuites.TestSuite3_Login" name="validateGoogleLink" time="5.645">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testSuites.TestSuite3_Login.validateGoogleLink(TestSuite3_Login.java:117)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateGoogleLink -->
  <testcase classname="testSuites.TestSuite1_UpcomingHondaBikes" name="validateManufacturerDropdown" time="10.06">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testSuites.TestSuite1_UpcomingHondaBikes.validateManufacturerDropdown(TestSuite1_UpcomingHondaBikes.java:140)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- validateManufacturerDropdown -->
  <testcase classname="testSuites.TestSuite2_UsedCarsInChennai" name="validatePopularModelsIsDisplayed" time="0.055"/>
  <testcase classname="testSuites.TestSuite3_Login" name="captureErrorMessafeWithInvalidMail" time="10.062">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testSuites.TestSuite3_Login.captureErrorMessafeWithInvalidMail(TestSuite3_Login.java:158)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- captureErrorMessafeWithInvalidMail -->
</testsuite> <!-- ZigWheels(Edge)-Test -->
